# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NameGenerator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='firstname',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='lastname',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
